obs/slapos: Add missing dependencies
This adds the following SlapOS dependencies:

- awk: This is required implicitly by some SlapOS packages (it is
  assumed to exist). For example, ncurses:

  ```
  configure: error: No awk program found
  ```

- iproute2: This is required explicitly by `slapos node format` when
  `alter_network=True`:

  ```
  Some required binaries are missing or not functional: ip
  ```

- procps: This is also required by `slapos node format` when
  `alter_network=True`, as it uses sysctl:

  ```
  FileNotFoundError: [Errno 2] No such file or directory: 'sysctl': 'sysctl'
  ```

See nexedi/slapos.package!211
See nexedi/slapos.core!655 for additional context.