re6st: fix build of gettext
Since debian/compat is increased to 9, stricter flags are used for compilation.

With default dpkg-buildflags, gettext fails to build as follows:

libcroco/cr-statement.c: In function 'cr_statement_dump_ruleset':
libcroco/cr-statement.c:2610:17: error: format not a string literal and no format arguments [-Werror=format-security]
                 fprintf (a_fp, str);
                 ^